---
title: "Homework_03"
output:
  html_document:
    theme: cosmo
  pdf_document: default
---
### First Problem
Given format:

  First String    Second      1.22      3.4   
  Second          More Text   1.555555  2.2220   
  Third           x           3         124   
```
FIND: \t+
REPLACE:,
```
Solved format:

First String,Second,1.22,3.4   
Second,More Text,1.555555,2.2220   
Third,x,3,124   

I replaced all tabs that were separating the columns with commas

### Second Problem
Given format:

Ballif, Bryan, University of Vermont   
Ellison, Aaron, Harvard Forest   
Record, Sydne, Bryn Mawr   

```
FIND: (\w*). (\w*). (\w+ \w.*)
REPLACE: \2 \1 (\3)
```
Solved format:

Bryan Ballif (University of Vermont)   
Aaron Ellison (Harvard Forest)   
Sydne Record (Bryn Mawr)   

I captured just the first and last names and replaced with the first name before the last. I then captured the University name and replaced with added parentheses.

### Third Problem
Given format:

0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 0003 Cherokee Shuffle.mp3 0004 Walking Cane.mp3

```
FIND:(\.\w+ )
REPLACE:\1\n
```
Solved format:

0001 Georgia Horseshoe.mp3   
0002 Billy In The Lowground.mp3   
0003 Cherokee Shuffle.mp3   
0004 Walking Cane.mp3   

Captured each .mp3 and replaced it with itself followed by a new line break (\n)

### Forth Problem
Given format:

0001 Georgia Horseshoe.mp3   
0002 Billy In The Lowground.mp3   
0003 Cherokee Shuffle.mp3   
0004 Walking Cane.mp3   
```
FIND: (\d{4})( \w.*)(\.\w+)
REPLACE:\2_\1\3
```
Solved format:

Georgia Horseshoe_0001.mp3   
Billy In The Lowground_0002.mp3   
Cherokee Shuffle_0003.mp3   
Walking Cane_0004.mp3   

I separated the number, name of the song and .mp3 and captured each. I used curly brackets to indicate I wanted 4 numbers to capture only the 4 numbers I wanted. I then rearranged the captures in the format wanted

### Fifth Problem
Given format:

Camponotus,pennsylvanicus,10.2,44   
Camponotus,herculeanus,10.5,3   
Myrmica,punctiventris,12.2,4   
Lasius,neoniger,3.3,55   
```
FIND:(\w)\w+,(\w+,)\w.*,(\w+)
REPLACE: \1_\2\3
```
Solved format:

C_pennsylvanicus,44   
C_herculeanus,3   
M_punctiventris,4   
L_neoniger,55   

I captured the first letter of the first word, the entire second word and the digits after the last comma (second number) and replaced with just what was captured, adding the neccessary underline. 

### Sixth Problem
Given format:

Camponotus,pennsylvanicus,10.2,44   
Camponotus,herculeanus,10.5,3   
Myrmica,punctiventris,12.2,4   
Lasius,neoniger,3.3,55   
```
FIND:(\w)\w+,(\w{4})\w.*,(\w+)
REPLACE: \1_\2,\3
```
Solved format:

C_penn,44   
C_herc,3   
M_punc,4   
L_neon,55   

I captured just the first letter of the first word, the first four letters of the second word and the last number.

### Seventh Problem
Given format:

Camponotus,pennsylvanicus,10.2,44   
Camponotus,herculeanus,10.5,3   
Myrmica,punctiventris,12.2,4   
Lasius,neoniger,3.3,55   

```
FIND:(\w{3})\w+,(\w{3})\w+,(\w.*),(\w+)
REPLACE:\1\2, \4, \3
```
Solved Format:

Campen, 44, 10.2   
Camher, 3, 10.5   
Myrpun, 4, 12.2   
Lasneo, 55, 3.3   

I captured the first three letters of the first and second word as the first and second captures. I then captured the two sets of numbers as the third and fourth captures. 